Fix parse reward event index error
opentensor/text-prompting pull request #77
Opened 2023-11-17 15:46 UTC by isabella618033

File "/home/bts/text-prompting/prompting/validators/reward/reward.py", line 33, in parse_reward_events
field_names = [field.name for field in fields(reward_events[0])]
IndexError: list index out of range

2023-11-17 21:02 UTC, p-ferreira commented
It would be nice to have some unit tests around this function

2023-11-17 21:04 UTC, p-ferreira requested changes
It would be nice to have some unit tests around this function, two would be enough:
- one test to validate that the function behaves as expected when given reward events
- one test to validate that the function behaves as expected when given no reward events

2023-11-20 18:08 UTC, Eugene-hu approved these changes

2023-11-20 18:19 UTC, p-ferreira approved these changes

2023-11-20 18:20 UTC, merged